CREATE TABLE source (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    kind TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE scope (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    description TEXT NOT NULL DEFAULT '',
    include_terms TEXT[] NOT NULL DEFAULT '{}',
    exclude_terms TEXT[] NOT NULL DEFAULT '{}',
    categories TEXT[] NOT NULL DEFAULT '{}',
    date_from DATE,
    date_to DATE,
    per_source_limit INTEGER NOT NULL DEFAULT 100,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE paper (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doi TEXT,
    arxiv_id TEXT,
    openalex_id TEXT,
    s2_id TEXT,
    title TEXT NOT NULL,
    abstract TEXT,
    published_at DATE,
    venue TEXT,
    is_preprint BOOLEAN NOT NULL DEFAULT false,
    oa_status TEXT,
    pdf_path TEXT,
    tei_xml TEXT,
    parse_status TEXT NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_paper_doi UNIQUE (doi),
    CONSTRAINT uq_paper_arxiv_id UNIQUE (arxiv_id)
);

CREATE TABLE paper_author (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paper_id BIGINT NOT NULL REFERENCES paper(id) ON DELETE CASCADE,
    position INTEGER NOT NULL,
    full_name TEXT NOT NULL
);

CREATE TABLE paper_source (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paper_id BIGINT NOT NULL REFERENCES paper(id) ON DELETE CASCADE,
    source_id BIGINT NOT NULL REFERENCES source(id) ON DELETE RESTRICT,
    external_id TEXT NOT NULL,
    retrieved_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE paper_scope (
    paper_id BIGINT NOT NULL REFERENCES paper(id) ON DELETE CASCADE,
    scope_id BIGINT NOT NULL REFERENCES scope(id) ON DELETE CASCADE,
    PRIMARY KEY (paper_id, scope_id)
);

CREATE TABLE section (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paper_id BIGINT NOT NULL REFERENCES paper(id) ON DELETE CASCADE,
    parent_id BIGINT REFERENCES section(id) ON DELETE CASCADE,
    section_path TEXT NOT NULL,
    title TEXT,
    ordinal INTEGER NOT NULL,
    page_start INTEGER,
    page_end INTEGER,
    char_start INTEGER,
    char_end INTEGER,
    body_text TEXT NOT NULL DEFAULT ''
);

CREATE TABLE ingest_job (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_id BIGINT NOT NULL REFERENCES scope(id) ON DELETE CASCADE,
    state TEXT NOT NULL,
    papers_found INTEGER NOT NULL DEFAULT 0,
    papers_parsed INTEGER NOT NULL DEFAULT 0,
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at TIMESTAMPTZ,
    error TEXT
);
