CREATE TABLE tree_node (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paper_id BIGINT NOT NULL REFERENCES paper(id) ON DELETE CASCADE,
    section_id BIGINT NOT NULL REFERENCES section(id) ON DELETE CASCADE,
    parent_id BIGINT REFERENCES tree_node(id) ON DELETE CASCADE,
    node_path TEXT NOT NULL,
    title TEXT,
    summary TEXT NOT NULL,
    page_start INTEGER,
    page_end INTEGER,
    depth INTEGER NOT NULL,
    tree_schema_version TEXT NOT NULL,
    summary_model TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX ix_tree_node_staleness
    ON tree_node (paper_id, tree_schema_version, summary_model);

CREATE TABLE retrieval_trace (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question TEXT NOT NULL,
    scope_id BIGINT NOT NULL REFERENCES scope(id) ON DELETE CASCADE,
    expanded_node_ids BIGINT[] NOT NULL DEFAULT '{}',
    selected_node_ids BIGINT[] NOT NULL DEFAULT '{}',
    nodes_expanded INTEGER NOT NULL,
    stopped_reason TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_retrieval_trace_stopped_reason CHECK (
        stopped_reason IN ('sufficient_evidence', 'budget_exhausted', 'no_candidates')
    )
);
