CREATE TABLE claim (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paper_id BIGINT NOT NULL REFERENCES paper(id) ON DELETE CASCADE,
    tree_node_id BIGINT NOT NULL REFERENCES tree_node(id) ON DELETE CASCADE,
    claim_text TEXT NOT NULL,
    normalized_text TEXT NOT NULL,
    claim_type TEXT NOT NULL,
    subject TEXT,
    predicate TEXT,
    object_value DOUBLE PRECISION,
    unit TEXT,
    canonical_claim_id BIGINT REFERENCES claim(id) ON DELETE SET NULL,
    extraction_model TEXT NOT NULL,
    prompt_version TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE method (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paper_id BIGINT NOT NULL REFERENCES paper(id) ON DELETE CASCADE,
    tree_node_id BIGINT NOT NULL REFERENCES tree_node(id) ON DELETE CASCADE,
    method_text TEXT NOT NULL,
    extraction_model TEXT NOT NULL,
    prompt_version TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paper_id BIGINT NOT NULL REFERENCES paper(id) ON DELETE CASCADE,
    tree_node_id BIGINT NOT NULL REFERENCES tree_node(id) ON DELETE CASCADE,
    result_text TEXT NOT NULL,
    extraction_model TEXT NOT NULL,
    prompt_version TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE dataset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paper_id BIGINT NOT NULL REFERENCES paper(id) ON DELETE CASCADE,
    tree_node_id BIGINT NOT NULL REFERENCES tree_node(id) ON DELETE CASCADE,
    dataset_name TEXT NOT NULL,
    description TEXT,
    extraction_model TEXT NOT NULL,
    prompt_version TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE metric (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paper_id BIGINT NOT NULL REFERENCES paper(id) ON DELETE CASCADE,
    tree_node_id BIGINT NOT NULL REFERENCES tree_node(id) ON DELETE CASCADE,
    metric_name TEXT NOT NULL,
    object_value DOUBLE PRECISION,
    unit TEXT,
    extraction_model TEXT NOT NULL,
    prompt_version TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE claim_evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id BIGINT NOT NULL REFERENCES claim(id) ON DELETE CASCADE,
    tree_node_id BIGINT NOT NULL REFERENCES tree_node(id) ON DELETE CASCADE,
    paper_id BIGINT NOT NULL REFERENCES paper(id) ON DELETE CASCADE,
    stance TEXT NOT NULL,
    rationale_text TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_claim_evidence_stance CHECK (
        stance IN ('supports', 'refutes', 'mentions')
    )
);

CREATE TABLE claim_score (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id BIGINT NOT NULL REFERENCES claim(id) ON DELETE CASCADE,
    confidence INTEGER NOT NULL,
    evidence_quality INTEGER NOT NULL,
    rubric_version TEXT NOT NULL,
    scored_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
