CREATE TABLE claim_extraction_observation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id BIGINT NOT NULL REFERENCES claim(id) ON DELETE CASCADE,
    paper_id BIGINT NOT NULL REFERENCES paper(id) ON DELETE CASCADE,
    tree_node_id BIGINT NOT NULL REFERENCES tree_node(id) ON DELETE CASCADE,
    claim_text TEXT NOT NULL,
    extraction_model TEXT NOT NULL,
    prompt_version TEXT NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO claim_extraction_observation (
    claim_id,
    paper_id,
    tree_node_id,
    claim_text,
    extraction_model,
    prompt_version,
    recorded_at
)
SELECT
    id,
    paper_id,
    tree_node_id,
    claim_text,
    extraction_model,
    prompt_version,
    created_at
FROM claim;
