CREATE TABLE discourse_source (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    kind TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT true,
    last_polled_at TIMESTAMPTZ
);

CREATE TABLE discourse_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id BIGINT NOT NULL REFERENCES discourse_source(id) ON DELETE CASCADE,
    external_id TEXT NOT NULL,
    url TEXT NOT NULL,
    title TEXT,
    author TEXT,
    posted_at TIMESTAMPTZ,
    score INTEGER,
    num_comments INTEGER,
    retrieved_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_discourse_item_source_external UNIQUE (source_id, external_id)
);

CREATE TABLE discourse_mention (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discourse_item_id BIGINT NOT NULL REFERENCES discourse_item(id) ON DELETE CASCADE,
    paper_id BIGINT NOT NULL REFERENCES paper(id) ON DELETE CASCADE,
    resolved_by TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_discourse_mention_resolved_by CHECK (
        resolved_by IN ('arxiv', 'doi')
    )
);

CREATE TABLE subscription (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind TEXT NOT NULL,
    scope_id BIGINT REFERENCES scope(id) ON DELETE CASCADE,
    claim_id BIGINT REFERENCES claim(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    active BOOLEAN NOT NULL DEFAULT true,
    CONSTRAINT ck_subscription_kind CHECK (
        kind IN ('topic', 'claim')
    ),
    CONSTRAINT ck_subscription_exactly_one_target CHECK (
        (scope_id IS NOT NULL AND claim_id IS NULL)
        OR (scope_id IS NULL AND claim_id IS NOT NULL)
    )
);

CREATE TABLE sweep_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind TEXT NOT NULL,
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at TIMESTAMPTZ,
    state TEXT NOT NULL,
    items_found INTEGER NOT NULL DEFAULT 0,
    error TEXT,
    CONSTRAINT ck_sweep_run_kind CHECK (
        kind IN ('evidence', 'discourse')
    )
);
